# See docs
# https://www.netlify.com/docs/netlify-toml-reference/
# https://www.netlify.com/docs/redirects/

[[redirects]]
  from = "http://www.foretold.io/*"
  to = "https://www.foretold.io/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
