version: "2"

services:

  app:
    environment:
      - API_URL=http://chane-me/graphql
      - BOT_TOKEN=<change-me>
      - BOT_AGENT_ID=<change-me>
      - CDF_COMBINE_SIZE=1000
      - AGGR_SCHEDULE=0 * * * *

