sudo: required

services:
  - docker
  - postgresql

branches:
  only:
    - master
    - develop
    - master-server

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=foretold-app/foretold
    - DOCKER_COMPOSE_VERSION=1.8.1
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - DB_DATABASE=travis_ci_test
    - DB_HOST=localhost

before_script:
  - echo Before-Script-OK
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - printenv
  - docker build -t main ./
  - docker exec -d main yarn server/db:migrate
#  - docker run main yarn packages/build
#  - docker run main yarn packages/test
#  - docker run main yarn packages/lint
