sudo: required

services:
  - docker

branches:
  only:
    - master
    - develop
    - master-server

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=foretold-app/foretold
    - DOCKER_COMPOSE_VERSION=1.8.1

before_install:
  - echo Before-Install-OK

before_script:
  - echo Before-Script-OK

install:
  - docker build -t main ./

script:
  - printenv
  - docker run main npm run server/test:ci
