language: generic

services:
  - docker

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

branches:
  only:
    - master
    - develop
    - master-server

env:
  global:
    - PGPORT=5433
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=foretold-app/foretold
    - DOCKER_COMPOSE_VERSION=1.8.1
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - DB_DATABASE=travis_ci_test
    - DB_HOST=localhost

before_script:
  - echo Before-Script-OK

install:
  - docker build -t main ./
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - printenv
  - docker ps -a
  - docker run main yarn server/db:migrate
#  - docker run main yarn packages/build
#  - docker run main yarn packages/test
#  - docker run main yarn packages/lint
