version: "2"

services:

  app:
    build: ./
    restart: always
    environment:
      - PORT=80
      - NODE_PATH=/opt/app
    command: yarn start
    expose:
      - 80

  database:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_PASSWORD=changeMe

  # Load Balancer
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
