version: "2"

services:

  app:
#    volumes:
#      - ./packages:/opt/app/packages
    environment:
      # 1. Persistence
      # - PORT=80 # 1.1
      # - NODE_PATH=/opt/app # 1.2
      # - NODE_ENV=development # 1.3
      # 2. Auth0 (change)
      - AUTH0_SECRET=someSecretStringWithLengthUpToSixtyFourChars # 2.1 (change)
      - AUTH0_DOMAIN=example.auth0.com # 2.2 (change)
      - AUTH0_CLIENT_ID=someClientIDUpToFourtyChars # 2.3 (change)
      # 3. Main
      - API_URL=http://localhost/graphql # 3.1 (change)
      - SERVER_URL=http://localhost # 3.1.1 (change)
      # - CDF_COMBINE_SIZE=1000 # 3.2
      # - AGGR_SCHEDULE=0 * * * * # 3.3
      - SLACK_WEBHOOK_URL=<change-me> # 3.4  (change)
      - BOT_TOKEN=someTokenStringWithALengthUpToSixtyFourCharsGetItFromApplication # 3.5  (change)
      # - JWT_ISSUER=Foretold # 3.6
      - JWT_SECRET=anotherRandomSecretString # 3.7  (change)
      - INTERCOM_APP_ID=changeString # 3.8 (change)
      # 4. SMTP
      - SMTP_HOST=some-smtp-gateway.domain.com # 4.1 (change)
      # - SMTP_PORT=465 # 4.2
      - SMTP_USER=someuser # 4.3 (change)
      - SMTP_PASS=somepassword # 4.4 (change)
      - SMTP_FROM=UserName <userbox@host.com> # 4.5 (change)
      # 5. GitHub. You must be owner of the repo.
      - GITHUB_PERSONAL_ACCESS_TOKEN=someStringOfPersonalAccessToken # 5.1  (change)
      - GITHUB_REPO_OWNER=repo-owner # 5.2 (change)
      - GITHUB_REPO_NAME=repo-name # 5.3 (change)
      - GITHUB_WEBHOOK_SECRET=someRandomSecretString # 5.4 (change)
      # 6. Logging.
      - GOOGLE_AUTH={"jsonObjectsAsString":true} # 6.1 (change)
      - LOG_LEVEL_LOCAL=trace # 6.2
      - LOG_LEVEL_REMOTE=trace # 6.3
      - LOG_APP_NAME=foretold # 6.4
      # 7. DB
      - DB_USERNAME=postgres # 6.1
      - DB_PASSWORD=password # 6.2
      - DB_DATABASE=development # 6.3
      - DB_HOST=database # 6.4
      # - DB_USE_ENV_VARIABLE=DATABASE_URL # 6.5
    command: yarn dev
    links:
      - database

  database:
    volumes:
      - ./.persistence/database-main:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password # 6.2

  nginx:
    links:
      - app
    ports:
      - "80:4000"
