version: "2"

services:

  app:
    build: ./
    environment:
      # 1. Persistence
      - PORT=80 # 1.1
      - NODE_PATH=/opt/app # 1.2
      - NODE_ENV=development # 1.3
      # 2. Auth0
      - AUTH0_SECRET=<change-me> # 2.1
      - AUTH0_DOMAIN=<change-me> # 2.2
      - AUTH0_CLIENT_ID=<change-me> # 2.3
      # 3. Main
      - API_URL=<change-me> # 3.1
      - SERVER_URL=<change-me> # 3.1.1
      - CDF_COMBINE_SIZE=1000 # 3.2
      - AGGR_SCHEDULE=0 * * * * # 3.3
      - SLACK_WEBHOOK_URL=<change-me> # 3.4
      - BOT_TOKEN=<change-me> # 3.5
      - JWT_ISSUER=Foretold # 3.6
      - JWT_SECRET=<change-me> # 3.7
      # 4. SMTP
      - SMTP_HOST=<change-me> # 4.1
      - SMTP_PORT=465 # 4.2
      - SMTP_USER=<change-me> # 4.3
      - SMTP_PASS=<change-me> # 4.4
      - SMTP_FROM=<change-me> # 4.5
      # 5. GitHub. You must be owner of the repo.
      - GITHUB_PERSONAL_ACCESS_TOKEN=<change-me> # 5.1
      - GITHUB_REPO_OWNER=foretold-app # 5.2
      - GITHUB_REPO_NAME=ken-data # 5.3
      - GITHUB_WEBHOOK_SECRET=<change-me> # 5.4
    command: npm start
    links:
      - database

  database:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=<change-me>
