version: "2"

services:

  app:
    build: ./
    environment:
      # Persistence
      - PORT=80
      - NODE_PATH=/opt/app
      # Need to change
      - AUTH0_SECRET=<change-me>
      - SLACK_WEBHOOK_URL=<change-me>
      - JWT_SECRET=<change-me>
      - JWT_ISSUER=Foretold
      - BOT_TOKEN=<change-me>
      - BOT_AGENT_ID=<change-me>
      - CDF_COMBINE_SIZE=1000
    command: npm start
    links:
      - database

  database:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=<change-me>
