version: "2"

services:

  app:
    environment:
      - AUTH0_SECRET=<change-me>
      - SLACK_WEBHOOK_URL=<change-me>
      - PORT=80
      - JWT_SECRET=<change-me>
      - JWT_ISSUER=Foretold
      - API_URL=http://chane-me/graphql
      - BOT_TOKEN=<change-me>

  database:
    environment:
      - POSTGRES_PASSWORD=<change-me>
